name: CI

on:
  push:
    branches:
      - master
      - 'dependabot/*'
    paths:
      - '*'
      - '!*.md'
  pull_request:
    branches:
      - master
    paths:
      - '*'
      - '!*.md'

jobs:
  lint:
    name: Lint on ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install latest npm
      run: npm install --global npm@latest && node -v && npm -v

    - name: npm install, and pretest
      run: node -v && npm -v && npm install && npm run pretest && node -v && npm -v

  test:
    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: ubuntu-latest
            node-version: 10

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install latest npm
      run: npm install --global npm@latest && node -v && npm -v

    - name: npm install, and test
      run: node -v && npm -v && npm install && npm run jest -- --ci && node -v && npm -v

  coverage:
    name: Test coverage on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install latest npm
      run: npm install --global npm@latest && node -v && npm -v

    - name: npm install, and test
      run: node -v && npm -v && npm install && npm run jest -- --coverage --ci && node -v && npm -v

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true
        path-to-lcov: ./.coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
