name: CI

on:
  push:
    branches:
      - master
      - 'dependabot/*'
    paths:
      - '*'
      - '!*.md'
  pull_request:
    branches:
      - master
    paths:
      - '*'
      - '!*.md'

jobs:
  lint:
    name: Lint on ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, and pretest
      run: npm install && npm run pretest
      env:
        CI: pretest

  test:
    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: ubuntu-latest
            node-version: 10

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, and test
      run: npm install && npm run jest
      env:
        CI: true

  coverage:
    name: Test coverage on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, and test
      run: npm install && npm run jest --coverage
      env:
        CI: true

    - name: Coveralls Parallel
      uses: vankop/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true
        path-to-lcov: ./.coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
